title: Ayomide Okeowo
logo: image
description: Data Scientist | MSc in Applied Data Science | Passionate about turning data into actionable insights
show_downloads: true
Theme: jekyll-theme-minimal


