title: Ayomide Okeowo
logo: /assets/img/headshot_circle.png
description: Data Scientist | MSc in Applied Data Science | Passionate about turning data into actionable insights
show_downloads: true
Theme: jekyll-theme-minimal


